### ISSUE TITLE
Current Modrinth release crashes on boot.

### ISSUE THREAD

**Issue by tractorbeam0** [zaidenCo/noSleepMod#2]
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [nosleep.mixins.json:ExampleMixin from mod nosleep] from phase [DEFAULT] in config [nosleep.mixins.json] FAILED during PREPARE`

Obviously that has nothing to do with other mods, but just to be sure I tried the mod with the fabric api by themselves. I'm not seeing any ExampleMixin in the github codebase, maybe something went wrong during compilation? Although I don't know how compilation works in java at all, let alone minecraft mods, so you be the judge of that.

**Comment by zaidenCo** [comment]
Apologies, I have not been up-to-date with my new mods. I am now back on modrinth and updating all previous mods.

**Comment by zaidenCo** [comment]
A new version has been published.
